version: '3'

services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    ports:
      - "27018:27017"
  esms2:
    image: esms1
    container_name: "esms2"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/esms
    ports:
      - "8082:8080"